### ISSUE TITLE
source file for quests in kyo-chatgpt

### ISSUE THREAD

**Issue by giuliohome** [getkyo/kyo#17]
I am testing the demo of ChatGPT with the new effect for AI Quests.
The current version of the code is copied from this [gist](https://gist.github.com/fwbrasil/ea56f7f4e97c9966251db2031c224b7e) and my exact git repo is [here](https://github.com/giuliohome/AIQuestKyoEffect/blob/main/src/main/scala/example/Hello.scala).

It `sbt compile` but there is a runtime exception:
```
[giulio@fedora mykyo]$ sbt run
[info] welcome to sbt 1.8.2 (Red Hat, Inc. Java 19.0.2)
[info] loading project definition from /home/giulio/scala/mykyo/project
[info] loading settings for project hello from build.sbt ...
[info] set current project to Hello (in build file:/home/giulio/scala/mykyo/)
[info] compiling 1 Scala source to /home/giulio/scala/mykyo/target/scala-3.2.2/classes ...
[warn] there was 1 feature warning; re-run with -feature for details
[warn] one warning found
[info] running Hello 
[error] java.io.FileNotFoundException: /home/runner/work/kyo/kyo/kyo-chatgpt/src/main/scala/kyo/quests.scala (No such file or directory)
[error]         at java.base/java.io.FileInputStream.open0(Native Method)
[error]         at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[error]         at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
[error]         at scala.io.Source$.fromFile(Source.scala:94)
[error]         at scala.io.Source$.fromFile(Source.scala:79)
[error]         at scala.io.Source$.fromFile(Source.scala:57)
[error]         at kyo.quests$Quests$.observe(quests.scala:169)
[error]         at kyo.quests$Quests$.$anonfun$1$$anonfun$1$$anonfun$1(quests.scala:146)
[error]         at kyo.core$.kyo$core$$$_$transformLoop$1(core.scala:146)
[error]         at kyo.core$$anon$5.apply(core.scala:142)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.ios$IOs$$anon$2.apply(ios.scala:81)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$.shallowHandleLoop$1$$anonfun$1(core.scala:199)
[error]         at kyo.sums$Sums$given_Handler_Sum_Sums$2$.apply(sums.scala:48)
[error]         at kyo.core$.kyo$core$$$_$shallowHandleLoop$1(core.scala:199)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.ios$IOs$$anon$2.apply(ios.scala:81)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.core$$anon$5.apply(core.scala:138)
[error]         at kyo.ios$IOs$$anon$2.apply(ios.scala:81)
[error]         at kyo.core$$anon$8.liftedTree1$1(core.scala:209)
[error]         at kyo.core$$anon$8.apply(core.scala:213)
[error]         at kyo.concurrent.scheduler.IOTask.eval(IOTask.scala:109)
[error]         at kyo.concurrent.scheduler.IOTask.run(IOTask.scala:129)
[error]         at kyo.concurrent.scheduler.Worker.runWorker(Worker.scala:78)
[error]         at kyo.concurrent.scheduler.Scheduler$.startWorkers$$anonfun$1(Scheduler.scala:46)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1589)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.io.FileNotFoundException: /home/runner/work/kyo/kyo/kyo-chatgpt/src/main/scala/kyo/quests.scala (No such file or directory)
[error] Total time: 13 s, completed Apr 5, 2023, 6:44:39 PM
```
It looks like the above is the location of the source code when you have built the artifact into maven central and doesn't correspond to a path in my machine, should I rebuild the whole kyo repo on my machine or how is that source file supposed to be found?

Indeed I have cloned this kyo repo and [published it locally](https://www.scala-sbt.org/1.x/docs/Publishing.html#Publishing+locally).
Then I have [updated the build.sbt as follows](https://github.com/giuliohome/AIQuestKyoEffect/blob/fc77cccabc78e9100e0311bb16db9baeb04f548f/build.sbt#L15-L16)
```
    libraryDependencies += "giuliohome.com" % "kyo-chatgpt_3" % "0.0.0+266-77c10268+20230405-1250-SNAPSHOT",
    // libraryDependencies += "io.getkyo" % "kyo-chatgpt_3" % "0.2.5",
```
And now it works.

```
[giulio@fedora mykyo]$ sbt run
[info] welcome to sbt 1.8.2 (Red Hat, Inc. Java 19.0.2)
[info] loading project definition from /home/giulio/scala/mykyo/project
[info] loading settings for project hello from build.sbt ...
[info] set current project to Hello (in build file:/home/giulio/scala/mykyo/)
[info] compiling 1 Scala source to /home/giulio/scala/mykyo/target/scala-3.2.2/classes ...
[warn] there was 1 feature warning; re-run with -feature for details
[warn] one warning found
[info] running Hello 

Recipe(Spaghetti alla Carbonara,List(Step(Boil spaghetti in salted water until very al dente,10,Set(Ingredient(Spaghetti,10), Ingredient(salt,1))), Step(Fry the pancetta in a pan,5,Set(Ingredient(Pancetta,150), Ingredient(Olive oil,1), Ingredient(Pepper,1))), Step(Mix the beaten eggs and parmesan cheese in a bowl,5,Set(Ingredient(Eggs,2), Ingredient(Grated parmesan cheese,50), Ingredient(Pepper,1))), Step(Add the spaghetti to the pan, turn off the heat and pour the egg mixture in while mixing well until you have a creamy consistency,5,Set())))
[success] Total time: 67 s (01:07), completed Apr 5, 2023, 6:47:27 PM
```

Props to you for this very cool library! and keep up with the good work!

**Comment by giuliohome** [comment]
Out of my curiosity, looking at [my forked fix here](https://github.com/giuliohome/kyo/blob/abf82b897aea525338bed53e7e4d719d003f4f80/kyo-chatgpt/src/main/scala/kyo/quests.scala#L170-L184) (with this [resource generator in build.sbt](https://github.com/giuliohome/kyo/blob/abf82b897aea525338bed53e7e4d719d003f4f80/build.sbt#L181-L193)), while it actually reads the previously missing source from the jar instead of the user filesystem, now ChatGPT seems unable to understand the code or at least I see a timeout from the completions api, which doesn't happen with the original source code... any idea why it happens?
